version: '3'

services:
  zlmediakit-mcp-sse:
    build: 
      context: .
      dockerfile: Dockerfile
    image: zlmediakit-mcp-sse:latest
    container_name: zlmediakit-mcp-sse
    ports:
      - "8021:8020"
    command: ["python", "main.py", "--host", "0.0.0.0", "--port", "8020"]
  
  zlmediakit:
    image: zlmediakit/zlmediakit:master
    container_name: zlmediakit
    ports:
      - "1935:1935"
      - "8080:80"
      - "8443:443"
      - "8554:554"
      - "10000:10000"
      - "10000:10000/udp"
      - "8000:8000/udp"
      - "9000:9000/udp"